name: CI Workflow


on: push


jobs: 
  linting:
    runs-on: ubuntu-latest
  steps:
    name: checkout code
    uses: actions/checkout@v3 
    name: Setup python
    uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    name:  install dependancies
    run: |
          python -m pip install --upgrade pip
          pip install flake8

    name: run flake8
    run: 
        flake8 example.py 
